version: 2

sources:
  - name: person
    database: FEA24_11
    schema: RAW_ADVENTURE_WORKS
    tables:
      - name: address
        description: "Tabela com informações de endereços."
        columns:
          - name: addressid
            description: "Identificador único do endereço."
          - name: addressline1
            description: "Linha principal do endereço."
          - name: addressline2
            description: "Linha secundária do endereço (opcional)."
          - name: city
            description: "Cidade do endereço."
          - name: stateprovinceid
            description: "Identificador do estado ou província associado ao endereço."
          - name: postalcode
            description: "Código postal do endereço."

      - name: countryregion
        description: "Tabela com informações sobre países e regiões."
        columns:
          - name: countryregioncode
            description: "Código que identifica o país ou região."
          - name: countryregionname
            description: "Nome do país ou região."
          - name: modifieddate
            description: "Data de última modificação do registro."

      - name: person
        description: "Tabela com informações de pessoas, como nome, título e tipo."
        columns:
          - name: businessentityid
            description: "Chave primária para identificar a pessoa ou entidade."
          - name: persontype
            description: "Tipo da pessoa (cliente, funcionário, etc.)."
          - name: firstname
            description: "Primeiro nome da pessoa."
          - name: lastname
            description: "Sobrenome da pessoa."
          - name: emailpromotion
            description: "Indica se a pessoa optou por receber promoções por e-mail."

      - name: stateprovince
        description: "Tabela com informações sobre estados ou províncias."
        columns:
          - name: stateprovinceid
            description: "Identificador único do estado ou província."
          - name: stateprovincename
            description: "Nome do estado ou província."
          - name: countryregioncode
            description: "Código do país ou região associado."