version: 2

sources:
  - name: person
    database: FEA24_11
    schema: raw_adventure_works
    tables:
      - name: address
      - name: countryregion
      - name: person
      - name: stateprovince