version: 2

sources:
  - name: sales
    database: FEA24_11
    schema: raw_adventure_works
    tables:
      - name: creditcard
      - name: customer
      - name: salesorderdetail
      - name: salesorderheader
      - name: salesorderheadersalesreason
      - name: salesreason
      - name: salesperson
      - name: store