version: 2

sources:
  - name: sales
    database: FEA24_11
    schema: RAW_ADVENTURE_WORKS
    tables:
      - name: creditcard
        description: "Tabela com informações sobre cartões de crédito utilizados nas transações."
        columns:
          - name: creditcardid
            description: "Identificador único do cartão de crédito."
          - name: cardtype
            description: "Tipo do cartão de crédito (Visa, MasterCard, etc.)."
          - name: cardnumber
            description: "Número do cartão de crédito (hash ou obscurecido)."
          - name: expmonth
            description: "Mês de expiração do cartão de crédito."
          - name: expyear
            description: "Ano de expiração do cartão de crédito."
          - name: modifieddate
            description: "Data de última modificação do registro."

      - name: customer
        description: "Tabela com informações sobre os clientes da empresa."
        columns:
          - name: customerid
            description: "Identificador único do cliente."
          - name: accountnumber
            description: "Número da conta do cliente."
          - name: territoryid
            description: "Identificador do território associado ao cliente."
          - name: modifieddate
            description: "Data de última modificação do registro."

      - name: salesorderdetail
        description: "Tabela com detalhes dos pedidos de venda realizados."
        columns:
          - name: salesorderid
            description: "Chave estrangeira associada ao cabeçalho do pedido."
          - name: productid
            description: "Chave estrangeira associada ao produto no pedido."
          - name: orderqty
            description: "Quantidade do produto no pedido."
          - name: unitprice
            description: "Preço unitário do produto."
          - name: modifieddate
            description: "Data de última modificação do registro."

      - name: salesorderheader
        description: "Tabela com os cabeçalhos dos pedidos de venda."
        columns:
          - name: salesorderid
            description: "Identificador único do cabeçalho do pedido."
          - name: totaldue
            description: "Valor total devido no pedido."
          - name: orderdate
            description: "Data em que o pedido foi realizado."
          - name: modifieddate
            description: "Data de última modificação do registro."
      - name: salesorderheadersalesreason
        description: "Tabela que relaciona pedidos de venda aos seus respectivos motivos."
        columns:
          - name: salesorderid
            description: "Chave estrangeira associada ao cabeçalho do pedido."
          - name: salesreasonid
            description: "Chave estrangeira associada ao motivo da venda."
          - name: modifieddate
            description: "Data de última modificação do registro."
      - name: salesreason
        description: "Tabela com os motivos de venda associados aos pedidos."
        columns:
          - name: salesreasonid
            description: "Identificador único do motivo da venda."
          - name: reasonname
            description: "Nome do motivo da venda."
          - name: reasontype
            description: "Tipo do motivo (ex.: preço, promoção)."

      - name: store
        description: "Tabela com informações sobre as lojas associadas às vendas."
        columns:
          - name: businessentityid
            description: "Identificador único da loja."
          - name: name
            description: "Nome da loja."
          - name: salespersonid
            description: "Identificador do vendedor associado à loja."
          - name: modifieddate
            description: "Data de última modificação do registro."